CREATE TABLE ACCOUNTS AS(
    SELECT LOWER(FIRST_NAME || '.' || LAST_NAME) AS USERNAME, 
        FIRST_NAME || '.' || LAST_NAME || TO_CHAR(SYSDATE, 'YYYYMMDD') AS PASSWORD,
        1 AS STATUS
    FROM EMPLOYEES
);

SELECT DBMS_RANDOM.STRING('X', 15) AS PASSWORD
FROM ACCOUNTS;

--BLOCO ANONIMO
BEGIN
    UPDATE ACCOUNTS 
    SET password = DBMS_RANDOM.STRING('X', 20);
END;

CREATE OR REPLACE FUNCTION FN_PASSWORD_MASCARADE (P_PASSWORD VARCHAR2)
RETURN VARCHAR2
IS
    V_SENHA_MASCARADA VARCHAR2(30);
BEGIN
    SELECT DBMS_RANDOM.STRING('X',20)
    INTO V_SENHA_MASCARADA
    FROM DUAL;
    
    RETURN V_SENHA_MASCARADA;
END;

SELECT FN_PASSWORD_MASCARADE('fiap') 
FROM DUAL;
